// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slssteam_servicemethods.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_slssteam_5fservicemethods_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_slssteam_5fservicemethods_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_slssteam_5fservicemethods_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_slssteam_5fservicemethods_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class CContentServerDirectory_GetManifestRequestCode_Request;
struct CContentServerDirectory_GetManifestRequestCode_RequestDefaultTypeInternal;
extern CContentServerDirectory_GetManifestRequestCode_RequestDefaultTypeInternal _CContentServerDirectory_GetManifestRequestCode_Request_default_instance_;
class CContentServerDirectory_GetManifestRequestCode_Response;
struct CContentServerDirectory_GetManifestRequestCode_ResponseDefaultTypeInternal;
extern CContentServerDirectory_GetManifestRequestCode_ResponseDefaultTypeInternal _CContentServerDirectory_GetManifestRequestCode_Response_default_instance_;
class CPlayer_GetUserStats_Request;
struct CPlayer_GetUserStats_RequestDefaultTypeInternal;
extern CPlayer_GetUserStats_RequestDefaultTypeInternal _CPlayer_GetUserStats_Request_default_instance_;
class CPlayer_GetUserStats_Response;
struct CPlayer_GetUserStats_ResponseDefaultTypeInternal;
extern CPlayer_GetUserStats_ResponseDefaultTypeInternal _CPlayer_GetUserStats_Response_default_instance_;
class CPlayer_GetUserStats_Response_Stats;
struct CPlayer_GetUserStats_Response_StatsDefaultTypeInternal;
extern CPlayer_GetUserStats_Response_StatsDefaultTypeInternal _CPlayer_GetUserStats_Response_Stats_default_instance_;
class CPlayer_GetUserStats_Response_Unlock_Time;
struct CPlayer_GetUserStats_Response_Unlock_TimeDefaultTypeInternal;
extern CPlayer_GetUserStats_Response_Unlock_TimeDefaultTypeInternal _CPlayer_GetUserStats_Response_Unlock_Time_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CContentServerDirectory_GetManifestRequestCode_Request* Arena::CreateMaybeMessage<::CContentServerDirectory_GetManifestRequestCode_Request>(Arena*);
template<> ::CContentServerDirectory_GetManifestRequestCode_Response* Arena::CreateMaybeMessage<::CContentServerDirectory_GetManifestRequestCode_Response>(Arena*);
template<> ::CPlayer_GetUserStats_Request* Arena::CreateMaybeMessage<::CPlayer_GetUserStats_Request>(Arena*);
template<> ::CPlayer_GetUserStats_Response* Arena::CreateMaybeMessage<::CPlayer_GetUserStats_Response>(Arena*);
template<> ::CPlayer_GetUserStats_Response_Stats* Arena::CreateMaybeMessage<::CPlayer_GetUserStats_Response_Stats>(Arena*);
template<> ::CPlayer_GetUserStats_Response_Unlock_Time* Arena::CreateMaybeMessage<::CPlayer_GetUserStats_Response_Unlock_Time>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CPlayer_GetUserStats_Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CPlayer_GetUserStats_Request) */ {
 public:
  inline CPlayer_GetUserStats_Request() : CPlayer_GetUserStats_Request(nullptr) {}
  virtual ~CPlayer_GetUserStats_Request();
  explicit constexpr CPlayer_GetUserStats_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CPlayer_GetUserStats_Request(const CPlayer_GetUserStats_Request& from);
  CPlayer_GetUserStats_Request(CPlayer_GetUserStats_Request&& from) noexcept
    : CPlayer_GetUserStats_Request() {
    *this = ::std::move(from);
  }

  inline CPlayer_GetUserStats_Request& operator=(const CPlayer_GetUserStats_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPlayer_GetUserStats_Request& operator=(CPlayer_GetUserStats_Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CPlayer_GetUserStats_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const CPlayer_GetUserStats_Request* internal_default_instance() {
    return reinterpret_cast<const CPlayer_GetUserStats_Request*>(
               &_CPlayer_GetUserStats_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CPlayer_GetUserStats_Request& a, CPlayer_GetUserStats_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(CPlayer_GetUserStats_Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPlayer_GetUserStats_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CPlayer_GetUserStats_Request* New() const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Request>(nullptr);
  }

  CPlayer_GetUserStats_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Request>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CPlayer_GetUserStats_Request& from);
  void MergeFrom(const CPlayer_GetUserStats_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CPlayer_GetUserStats_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPlayer_GetUserStats_Request";
  }
  protected:
  explicit CPlayer_GetUserStats_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShaSchemaFieldNumber = 3,
    kSteamidFieldNumber = 1,
    kAppidFieldNumber = 2,
    kCrcStatsFieldNumber = 4,
  };
  // optional bytes sha_schema = 3;
  bool has_sha_schema() const;
  private:
  bool _internal_has_sha_schema() const;
  public:
  void clear_sha_schema();
  const std::string& sha_schema() const;
  void set_sha_schema(const std::string& value);
  void set_sha_schema(std::string&& value);
  void set_sha_schema(const char* value);
  void set_sha_schema(const void* value, size_t size);
  std::string* mutable_sha_schema();
  std::string* release_sha_schema();
  void set_allocated_sha_schema(std::string* sha_schema);
  private:
  const std::string& _internal_sha_schema() const;
  void _internal_set_sha_schema(const std::string& value);
  std::string* _internal_mutable_sha_schema();
  public:

  // optional uint64 steamid = 1;
  bool has_steamid() const;
  private:
  bool _internal_has_steamid() const;
  public:
  void clear_steamid();
  ::PROTOBUF_NAMESPACE_ID::uint64 steamid() const;
  void set_steamid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_steamid() const;
  void _internal_set_steamid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint32 appid = 2;
  bool has_appid() const;
  private:
  bool _internal_has_appid() const;
  public:
  void clear_appid();
  ::PROTOBUF_NAMESPACE_ID::uint32 appid() const;
  void set_appid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_appid() const;
  void _internal_set_appid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 crc_stats = 4;
  bool has_crc_stats() const;
  private:
  bool _internal_has_crc_stats() const;
  public:
  void clear_crc_stats();
  ::PROTOBUF_NAMESPACE_ID::uint32 crc_stats() const;
  void set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_crc_stats() const;
  void _internal_set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CPlayer_GetUserStats_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sha_schema_;
  ::PROTOBUF_NAMESPACE_ID::uint64 steamid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 appid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 crc_stats_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// -------------------------------------------------------------------

class CPlayer_GetUserStats_Response_Unlock_Time PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CPlayer_GetUserStats_Response.Unlock_Time) */ {
 public:
  inline CPlayer_GetUserStats_Response_Unlock_Time() : CPlayer_GetUserStats_Response_Unlock_Time(nullptr) {}
  virtual ~CPlayer_GetUserStats_Response_Unlock_Time();
  explicit constexpr CPlayer_GetUserStats_Response_Unlock_Time(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CPlayer_GetUserStats_Response_Unlock_Time(const CPlayer_GetUserStats_Response_Unlock_Time& from);
  CPlayer_GetUserStats_Response_Unlock_Time(CPlayer_GetUserStats_Response_Unlock_Time&& from) noexcept
    : CPlayer_GetUserStats_Response_Unlock_Time() {
    *this = ::std::move(from);
  }

  inline CPlayer_GetUserStats_Response_Unlock_Time& operator=(const CPlayer_GetUserStats_Response_Unlock_Time& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPlayer_GetUserStats_Response_Unlock_Time& operator=(CPlayer_GetUserStats_Response_Unlock_Time&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CPlayer_GetUserStats_Response_Unlock_Time& default_instance() {
    return *internal_default_instance();
  }
  static inline const CPlayer_GetUserStats_Response_Unlock_Time* internal_default_instance() {
    return reinterpret_cast<const CPlayer_GetUserStats_Response_Unlock_Time*>(
               &_CPlayer_GetUserStats_Response_Unlock_Time_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CPlayer_GetUserStats_Response_Unlock_Time& a, CPlayer_GetUserStats_Response_Unlock_Time& b) {
    a.Swap(&b);
  }
  inline void Swap(CPlayer_GetUserStats_Response_Unlock_Time* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPlayer_GetUserStats_Response_Unlock_Time* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CPlayer_GetUserStats_Response_Unlock_Time* New() const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response_Unlock_Time>(nullptr);
  }

  CPlayer_GetUserStats_Response_Unlock_Time* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response_Unlock_Time>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CPlayer_GetUserStats_Response_Unlock_Time& from);
  void MergeFrom(const CPlayer_GetUserStats_Response_Unlock_Time& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CPlayer_GetUserStats_Response_Unlock_Time* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPlayer_GetUserStats_Response.Unlock_Time";
  }
  protected:
  explicit CPlayer_GetUserStats_Response_Unlock_Time(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAchievementBitFieldNumber = 1,
    kUnlockTimeFieldNumber = 2,
  };
  // optional uint32 achievement_bit = 1;
  bool has_achievement_bit() const;
  private:
  bool _internal_has_achievement_bit() const;
  public:
  void clear_achievement_bit();
  ::PROTOBUF_NAMESPACE_ID::uint32 achievement_bit() const;
  void set_achievement_bit(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_achievement_bit() const;
  void _internal_set_achievement_bit(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional fixed32 unlock_time = 2;
  bool has_unlock_time() const;
  private:
  bool _internal_has_unlock_time() const;
  public:
  void clear_unlock_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 unlock_time() const;
  void set_unlock_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_unlock_time() const;
  void _internal_set_unlock_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CPlayer_GetUserStats_Response.Unlock_Time)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 achievement_bit_;
  ::PROTOBUF_NAMESPACE_ID::uint32 unlock_time_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// -------------------------------------------------------------------

class CPlayer_GetUserStats_Response_Stats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CPlayer_GetUserStats_Response.Stats) */ {
 public:
  inline CPlayer_GetUserStats_Response_Stats() : CPlayer_GetUserStats_Response_Stats(nullptr) {}
  virtual ~CPlayer_GetUserStats_Response_Stats();
  explicit constexpr CPlayer_GetUserStats_Response_Stats(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CPlayer_GetUserStats_Response_Stats(const CPlayer_GetUserStats_Response_Stats& from);
  CPlayer_GetUserStats_Response_Stats(CPlayer_GetUserStats_Response_Stats&& from) noexcept
    : CPlayer_GetUserStats_Response_Stats() {
    *this = ::std::move(from);
  }

  inline CPlayer_GetUserStats_Response_Stats& operator=(const CPlayer_GetUserStats_Response_Stats& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPlayer_GetUserStats_Response_Stats& operator=(CPlayer_GetUserStats_Response_Stats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CPlayer_GetUserStats_Response_Stats& default_instance() {
    return *internal_default_instance();
  }
  static inline const CPlayer_GetUserStats_Response_Stats* internal_default_instance() {
    return reinterpret_cast<const CPlayer_GetUserStats_Response_Stats*>(
               &_CPlayer_GetUserStats_Response_Stats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CPlayer_GetUserStats_Response_Stats& a, CPlayer_GetUserStats_Response_Stats& b) {
    a.Swap(&b);
  }
  inline void Swap(CPlayer_GetUserStats_Response_Stats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPlayer_GetUserStats_Response_Stats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CPlayer_GetUserStats_Response_Stats* New() const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response_Stats>(nullptr);
  }

  CPlayer_GetUserStats_Response_Stats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response_Stats>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CPlayer_GetUserStats_Response_Stats& from);
  void MergeFrom(const CPlayer_GetUserStats_Response_Stats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CPlayer_GetUserStats_Response_Stats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPlayer_GetUserStats_Response.Stats";
  }
  protected:
  explicit CPlayer_GetUserStats_Response_Stats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnlockTimesFieldNumber = 3,
    kStatIdFieldNumber = 1,
    kStatValueFieldNumber = 2,
  };
  // repeated .CPlayer_GetUserStats_Response.Unlock_Time unlock_times = 3;
  int unlock_times_size() const;
  private:
  int _internal_unlock_times_size() const;
  public:
  void clear_unlock_times();
  ::CPlayer_GetUserStats_Response_Unlock_Time* mutable_unlock_times(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Unlock_Time >*
      mutable_unlock_times();
  private:
  const ::CPlayer_GetUserStats_Response_Unlock_Time& _internal_unlock_times(int index) const;
  ::CPlayer_GetUserStats_Response_Unlock_Time* _internal_add_unlock_times();
  public:
  const ::CPlayer_GetUserStats_Response_Unlock_Time& unlock_times(int index) const;
  ::CPlayer_GetUserStats_Response_Unlock_Time* add_unlock_times();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Unlock_Time >&
      unlock_times() const;

  // optional uint32 stat_id = 1;
  bool has_stat_id() const;
  private:
  bool _internal_has_stat_id() const;
  public:
  void clear_stat_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 stat_id() const;
  void set_stat_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_stat_id() const;
  void _internal_set_stat_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 stat_value = 2;
  bool has_stat_value() const;
  private:
  bool _internal_has_stat_value() const;
  public:
  void clear_stat_value();
  ::PROTOBUF_NAMESPACE_ID::uint32 stat_value() const;
  void set_stat_value(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_stat_value() const;
  void _internal_set_stat_value(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CPlayer_GetUserStats_Response.Stats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Unlock_Time > unlock_times_;
  ::PROTOBUF_NAMESPACE_ID::uint32 stat_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 stat_value_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// -------------------------------------------------------------------

class CPlayer_GetUserStats_Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CPlayer_GetUserStats_Response) */ {
 public:
  inline CPlayer_GetUserStats_Response() : CPlayer_GetUserStats_Response(nullptr) {}
  virtual ~CPlayer_GetUserStats_Response();
  explicit constexpr CPlayer_GetUserStats_Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CPlayer_GetUserStats_Response(const CPlayer_GetUserStats_Response& from);
  CPlayer_GetUserStats_Response(CPlayer_GetUserStats_Response&& from) noexcept
    : CPlayer_GetUserStats_Response() {
    *this = ::std::move(from);
  }

  inline CPlayer_GetUserStats_Response& operator=(const CPlayer_GetUserStats_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline CPlayer_GetUserStats_Response& operator=(CPlayer_GetUserStats_Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CPlayer_GetUserStats_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const CPlayer_GetUserStats_Response* internal_default_instance() {
    return reinterpret_cast<const CPlayer_GetUserStats_Response*>(
               &_CPlayer_GetUserStats_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CPlayer_GetUserStats_Response& a, CPlayer_GetUserStats_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(CPlayer_GetUserStats_Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CPlayer_GetUserStats_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CPlayer_GetUserStats_Response* New() const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response>(nullptr);
  }

  CPlayer_GetUserStats_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CPlayer_GetUserStats_Response>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CPlayer_GetUserStats_Response& from);
  void MergeFrom(const CPlayer_GetUserStats_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CPlayer_GetUserStats_Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPlayer_GetUserStats_Response";
  }
  protected:
  explicit CPlayer_GetUserStats_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef CPlayer_GetUserStats_Response_Unlock_Time Unlock_Time;
  typedef CPlayer_GetUserStats_Response_Stats Stats;

  // accessors -------------------------------------------------------

  enum : int {
    kStatsFieldNumber = 4,
    kShaSchemaFieldNumber = 1,
    kSchemaFieldNumber = 3,
    kCrcStatsFieldNumber = 2,
  };
  // repeated .CPlayer_GetUserStats_Response.Stats stats = 4;
  int stats_size() const;
  private:
  int _internal_stats_size() const;
  public:
  void clear_stats();
  ::CPlayer_GetUserStats_Response_Stats* mutable_stats(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Stats >*
      mutable_stats();
  private:
  const ::CPlayer_GetUserStats_Response_Stats& _internal_stats(int index) const;
  ::CPlayer_GetUserStats_Response_Stats* _internal_add_stats();
  public:
  const ::CPlayer_GetUserStats_Response_Stats& stats(int index) const;
  ::CPlayer_GetUserStats_Response_Stats* add_stats();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Stats >&
      stats() const;

  // optional bytes sha_schema = 1;
  bool has_sha_schema() const;
  private:
  bool _internal_has_sha_schema() const;
  public:
  void clear_sha_schema();
  const std::string& sha_schema() const;
  void set_sha_schema(const std::string& value);
  void set_sha_schema(std::string&& value);
  void set_sha_schema(const char* value);
  void set_sha_schema(const void* value, size_t size);
  std::string* mutable_sha_schema();
  std::string* release_sha_schema();
  void set_allocated_sha_schema(std::string* sha_schema);
  private:
  const std::string& _internal_sha_schema() const;
  void _internal_set_sha_schema(const std::string& value);
  std::string* _internal_mutable_sha_schema();
  public:

  // optional bytes schema = 3;
  bool has_schema() const;
  private:
  bool _internal_has_schema() const;
  public:
  void clear_schema();
  const std::string& schema() const;
  void set_schema(const std::string& value);
  void set_schema(std::string&& value);
  void set_schema(const char* value);
  void set_schema(const void* value, size_t size);
  std::string* mutable_schema();
  std::string* release_schema();
  void set_allocated_schema(std::string* schema);
  private:
  const std::string& _internal_schema() const;
  void _internal_set_schema(const std::string& value);
  std::string* _internal_mutable_schema();
  public:

  // optional uint32 crc_stats = 2;
  bool has_crc_stats() const;
  private:
  bool _internal_has_crc_stats() const;
  public:
  void clear_crc_stats();
  ::PROTOBUF_NAMESPACE_ID::uint32 crc_stats() const;
  void set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_crc_stats() const;
  void _internal_set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CPlayer_GetUserStats_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Stats > stats_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sha_schema_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr schema_;
  ::PROTOBUF_NAMESPACE_ID::uint32 crc_stats_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// -------------------------------------------------------------------

class CContentServerDirectory_GetManifestRequestCode_Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CContentServerDirectory_GetManifestRequestCode_Request) */ {
 public:
  inline CContentServerDirectory_GetManifestRequestCode_Request() : CContentServerDirectory_GetManifestRequestCode_Request(nullptr) {}
  virtual ~CContentServerDirectory_GetManifestRequestCode_Request();
  explicit constexpr CContentServerDirectory_GetManifestRequestCode_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CContentServerDirectory_GetManifestRequestCode_Request(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  CContentServerDirectory_GetManifestRequestCode_Request(CContentServerDirectory_GetManifestRequestCode_Request&& from) noexcept
    : CContentServerDirectory_GetManifestRequestCode_Request() {
    *this = ::std::move(from);
  }

  inline CContentServerDirectory_GetManifestRequestCode_Request& operator=(const CContentServerDirectory_GetManifestRequestCode_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline CContentServerDirectory_GetManifestRequestCode_Request& operator=(CContentServerDirectory_GetManifestRequestCode_Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CContentServerDirectory_GetManifestRequestCode_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const CContentServerDirectory_GetManifestRequestCode_Request* internal_default_instance() {
    return reinterpret_cast<const CContentServerDirectory_GetManifestRequestCode_Request*>(
               &_CContentServerDirectory_GetManifestRequestCode_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CContentServerDirectory_GetManifestRequestCode_Request& a, CContentServerDirectory_GetManifestRequestCode_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(CContentServerDirectory_GetManifestRequestCode_Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CContentServerDirectory_GetManifestRequestCode_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CContentServerDirectory_GetManifestRequestCode_Request* New() const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Request>(nullptr);
  }

  CContentServerDirectory_GetManifestRequestCode_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Request>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  void MergeFrom(const CContentServerDirectory_GetManifestRequestCode_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CContentServerDirectory_GetManifestRequestCode_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CContentServerDirectory_GetManifestRequestCode_Request";
  }
  protected:
  explicit CContentServerDirectory_GetManifestRequestCode_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppBranchFieldNumber = 4,
    kBranchPasswordHashFieldNumber = 5,
    kAppIdFieldNumber = 1,
    kDepotIdFieldNumber = 2,
    kManifestIdFieldNumber = 3,
  };
  // optional string app_branch = 4;
  bool has_app_branch() const;
  private:
  bool _internal_has_app_branch() const;
  public:
  void clear_app_branch();
  const std::string& app_branch() const;
  void set_app_branch(const std::string& value);
  void set_app_branch(std::string&& value);
  void set_app_branch(const char* value);
  void set_app_branch(const char* value, size_t size);
  std::string* mutable_app_branch();
  std::string* release_app_branch();
  void set_allocated_app_branch(std::string* app_branch);
  private:
  const std::string& _internal_app_branch() const;
  void _internal_set_app_branch(const std::string& value);
  std::string* _internal_mutable_app_branch();
  public:

  // optional string branch_password_hash = 5;
  bool has_branch_password_hash() const;
  private:
  bool _internal_has_branch_password_hash() const;
  public:
  void clear_branch_password_hash();
  const std::string& branch_password_hash() const;
  void set_branch_password_hash(const std::string& value);
  void set_branch_password_hash(std::string&& value);
  void set_branch_password_hash(const char* value);
  void set_branch_password_hash(const char* value, size_t size);
  std::string* mutable_branch_password_hash();
  std::string* release_branch_password_hash();
  void set_allocated_branch_password_hash(std::string* branch_password_hash);
  private:
  const std::string& _internal_branch_password_hash() const;
  void _internal_set_branch_password_hash(const std::string& value);
  std::string* _internal_mutable_branch_password_hash();
  public:

  // optional uint32 app_id = 1;
  bool has_app_id() const;
  private:
  bool _internal_has_app_id() const;
  public:
  void clear_app_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 app_id() const;
  void set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_app_id() const;
  void _internal_set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 depot_id = 2;
  bool has_depot_id() const;
  private:
  bool _internal_has_depot_id() const;
  public:
  void clear_depot_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 depot_id() const;
  void set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_depot_id() const;
  void _internal_set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint64 manifest_id = 3;
  bool has_manifest_id() const;
  private:
  bool _internal_has_manifest_id() const;
  public:
  void clear_manifest_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_id() const;
  void set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_manifest_id() const;
  void _internal_set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:CContentServerDirectory_GetManifestRequestCode_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_branch_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr branch_password_hash_;
  ::PROTOBUF_NAMESPACE_ID::uint32 app_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 depot_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_id_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// -------------------------------------------------------------------

class CContentServerDirectory_GetManifestRequestCode_Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:CContentServerDirectory_GetManifestRequestCode_Response) */ {
 public:
  inline CContentServerDirectory_GetManifestRequestCode_Response() : CContentServerDirectory_GetManifestRequestCode_Response(nullptr) {}
  virtual ~CContentServerDirectory_GetManifestRequestCode_Response();
  explicit constexpr CContentServerDirectory_GetManifestRequestCode_Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CContentServerDirectory_GetManifestRequestCode_Response(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  CContentServerDirectory_GetManifestRequestCode_Response(CContentServerDirectory_GetManifestRequestCode_Response&& from) noexcept
    : CContentServerDirectory_GetManifestRequestCode_Response() {
    *this = ::std::move(from);
  }

  inline CContentServerDirectory_GetManifestRequestCode_Response& operator=(const CContentServerDirectory_GetManifestRequestCode_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline CContentServerDirectory_GetManifestRequestCode_Response& operator=(CContentServerDirectory_GetManifestRequestCode_Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CContentServerDirectory_GetManifestRequestCode_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const CContentServerDirectory_GetManifestRequestCode_Response* internal_default_instance() {
    return reinterpret_cast<const CContentServerDirectory_GetManifestRequestCode_Response*>(
               &_CContentServerDirectory_GetManifestRequestCode_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CContentServerDirectory_GetManifestRequestCode_Response& a, CContentServerDirectory_GetManifestRequestCode_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(CContentServerDirectory_GetManifestRequestCode_Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CContentServerDirectory_GetManifestRequestCode_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CContentServerDirectory_GetManifestRequestCode_Response* New() const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Response>(nullptr);
  }

  CContentServerDirectory_GetManifestRequestCode_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CContentServerDirectory_GetManifestRequestCode_Response>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  void MergeFrom(const CContentServerDirectory_GetManifestRequestCode_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CContentServerDirectory_GetManifestRequestCode_Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CContentServerDirectory_GetManifestRequestCode_Response";
  }
  protected:
  explicit CContentServerDirectory_GetManifestRequestCode_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kManifestRequestCodeFieldNumber = 1,
  };
  // optional uint64 manifest_request_code = 1;
  bool has_manifest_request_code() const;
  private:
  bool _internal_has_manifest_request_code() const;
  public:
  void clear_manifest_request_code();
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_request_code() const;
  void set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_manifest_request_code() const;
  void _internal_set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:CContentServerDirectory_GetManifestRequestCode_Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 manifest_request_code_;
  friend struct ::TableStruct_slssteam_5fservicemethods_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CPlayer_GetUserStats_Request

// optional uint64 steamid = 1;
inline bool CPlayer_GetUserStats_Request::_internal_has_steamid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Request::has_steamid() const {
  return _internal_has_steamid();
}
inline void CPlayer_GetUserStats_Request::clear_steamid() {
  steamid_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CPlayer_GetUserStats_Request::_internal_steamid() const {
  return steamid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CPlayer_GetUserStats_Request::steamid() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Request.steamid)
  return _internal_steamid();
}
inline void CPlayer_GetUserStats_Request::_internal_set_steamid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  steamid_ = value;
}
inline void CPlayer_GetUserStats_Request::set_steamid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_steamid(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Request.steamid)
}

// optional uint32 appid = 2;
inline bool CPlayer_GetUserStats_Request::_internal_has_appid() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Request::has_appid() const {
  return _internal_has_appid();
}
inline void CPlayer_GetUserStats_Request::clear_appid() {
  appid_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Request::_internal_appid() const {
  return appid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Request::appid() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Request.appid)
  return _internal_appid();
}
inline void CPlayer_GetUserStats_Request::_internal_set_appid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  appid_ = value;
}
inline void CPlayer_GetUserStats_Request::set_appid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Request.appid)
}

// optional bytes sha_schema = 3;
inline bool CPlayer_GetUserStats_Request::_internal_has_sha_schema() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Request::has_sha_schema() const {
  return _internal_has_sha_schema();
}
inline void CPlayer_GetUserStats_Request::clear_sha_schema() {
  sha_schema_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CPlayer_GetUserStats_Request::sha_schema() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Request.sha_schema)
  return _internal_sha_schema();
}
inline void CPlayer_GetUserStats_Request::set_sha_schema(const std::string& value) {
  _internal_set_sha_schema(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Request.sha_schema)
}
inline std::string* CPlayer_GetUserStats_Request::mutable_sha_schema() {
  // @@protoc_insertion_point(field_mutable:CPlayer_GetUserStats_Request.sha_schema)
  return _internal_mutable_sha_schema();
}
inline const std::string& CPlayer_GetUserStats_Request::_internal_sha_schema() const {
  return sha_schema_.Get();
}
inline void CPlayer_GetUserStats_Request::_internal_set_sha_schema(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CPlayer_GetUserStats_Request::set_sha_schema(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CPlayer_GetUserStats_Request.sha_schema)
}
inline void CPlayer_GetUserStats_Request::set_sha_schema(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CPlayer_GetUserStats_Request.sha_schema)
}
inline void CPlayer_GetUserStats_Request::set_sha_schema(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CPlayer_GetUserStats_Request.sha_schema)
}
inline std::string* CPlayer_GetUserStats_Request::_internal_mutable_sha_schema() {
  _has_bits_[0] |= 0x00000001u;
  return sha_schema_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CPlayer_GetUserStats_Request::release_sha_schema() {
  // @@protoc_insertion_point(field_release:CPlayer_GetUserStats_Request.sha_schema)
  if (!_internal_has_sha_schema()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return sha_schema_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CPlayer_GetUserStats_Request::set_allocated_sha_schema(std::string* sha_schema) {
  if (sha_schema != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sha_schema_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sha_schema,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CPlayer_GetUserStats_Request.sha_schema)
}

// optional uint32 crc_stats = 4;
inline bool CPlayer_GetUserStats_Request::_internal_has_crc_stats() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Request::has_crc_stats() const {
  return _internal_has_crc_stats();
}
inline void CPlayer_GetUserStats_Request::clear_crc_stats() {
  crc_stats_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Request::_internal_crc_stats() const {
  return crc_stats_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Request::crc_stats() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Request.crc_stats)
  return _internal_crc_stats();
}
inline void CPlayer_GetUserStats_Request::_internal_set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  crc_stats_ = value;
}
inline void CPlayer_GetUserStats_Request::set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_crc_stats(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Request.crc_stats)
}

// -------------------------------------------------------------------

// CPlayer_GetUserStats_Response_Unlock_Time

// optional uint32 achievement_bit = 1;
inline bool CPlayer_GetUserStats_Response_Unlock_Time::_internal_has_achievement_bit() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response_Unlock_Time::has_achievement_bit() const {
  return _internal_has_achievement_bit();
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::clear_achievement_bit() {
  achievement_bit_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Unlock_Time::_internal_achievement_bit() const {
  return achievement_bit_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Unlock_Time::achievement_bit() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.Unlock_Time.achievement_bit)
  return _internal_achievement_bit();
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::_internal_set_achievement_bit(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  achievement_bit_ = value;
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::set_achievement_bit(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_achievement_bit(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.Unlock_Time.achievement_bit)
}

// optional fixed32 unlock_time = 2;
inline bool CPlayer_GetUserStats_Response_Unlock_Time::_internal_has_unlock_time() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response_Unlock_Time::has_unlock_time() const {
  return _internal_has_unlock_time();
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::clear_unlock_time() {
  unlock_time_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Unlock_Time::_internal_unlock_time() const {
  return unlock_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Unlock_Time::unlock_time() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.Unlock_Time.unlock_time)
  return _internal_unlock_time();
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::_internal_set_unlock_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  unlock_time_ = value;
}
inline void CPlayer_GetUserStats_Response_Unlock_Time::set_unlock_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_unlock_time(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.Unlock_Time.unlock_time)
}

// -------------------------------------------------------------------

// CPlayer_GetUserStats_Response_Stats

// optional uint32 stat_id = 1;
inline bool CPlayer_GetUserStats_Response_Stats::_internal_has_stat_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response_Stats::has_stat_id() const {
  return _internal_has_stat_id();
}
inline void CPlayer_GetUserStats_Response_Stats::clear_stat_id() {
  stat_id_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Stats::_internal_stat_id() const {
  return stat_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Stats::stat_id() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.Stats.stat_id)
  return _internal_stat_id();
}
inline void CPlayer_GetUserStats_Response_Stats::_internal_set_stat_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  stat_id_ = value;
}
inline void CPlayer_GetUserStats_Response_Stats::set_stat_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_stat_id(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.Stats.stat_id)
}

// optional uint32 stat_value = 2;
inline bool CPlayer_GetUserStats_Response_Stats::_internal_has_stat_value() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response_Stats::has_stat_value() const {
  return _internal_has_stat_value();
}
inline void CPlayer_GetUserStats_Response_Stats::clear_stat_value() {
  stat_value_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Stats::_internal_stat_value() const {
  return stat_value_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response_Stats::stat_value() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.Stats.stat_value)
  return _internal_stat_value();
}
inline void CPlayer_GetUserStats_Response_Stats::_internal_set_stat_value(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  stat_value_ = value;
}
inline void CPlayer_GetUserStats_Response_Stats::set_stat_value(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_stat_value(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.Stats.stat_value)
}

// repeated .CPlayer_GetUserStats_Response.Unlock_Time unlock_times = 3;
inline int CPlayer_GetUserStats_Response_Stats::_internal_unlock_times_size() const {
  return unlock_times_.size();
}
inline int CPlayer_GetUserStats_Response_Stats::unlock_times_size() const {
  return _internal_unlock_times_size();
}
inline void CPlayer_GetUserStats_Response_Stats::clear_unlock_times() {
  unlock_times_.Clear();
}
inline ::CPlayer_GetUserStats_Response_Unlock_Time* CPlayer_GetUserStats_Response_Stats::mutable_unlock_times(int index) {
  // @@protoc_insertion_point(field_mutable:CPlayer_GetUserStats_Response.Stats.unlock_times)
  return unlock_times_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Unlock_Time >*
CPlayer_GetUserStats_Response_Stats::mutable_unlock_times() {
  // @@protoc_insertion_point(field_mutable_list:CPlayer_GetUserStats_Response.Stats.unlock_times)
  return &unlock_times_;
}
inline const ::CPlayer_GetUserStats_Response_Unlock_Time& CPlayer_GetUserStats_Response_Stats::_internal_unlock_times(int index) const {
  return unlock_times_.Get(index);
}
inline const ::CPlayer_GetUserStats_Response_Unlock_Time& CPlayer_GetUserStats_Response_Stats::unlock_times(int index) const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.Stats.unlock_times)
  return _internal_unlock_times(index);
}
inline ::CPlayer_GetUserStats_Response_Unlock_Time* CPlayer_GetUserStats_Response_Stats::_internal_add_unlock_times() {
  return unlock_times_.Add();
}
inline ::CPlayer_GetUserStats_Response_Unlock_Time* CPlayer_GetUserStats_Response_Stats::add_unlock_times() {
  // @@protoc_insertion_point(field_add:CPlayer_GetUserStats_Response.Stats.unlock_times)
  return _internal_add_unlock_times();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Unlock_Time >&
CPlayer_GetUserStats_Response_Stats::unlock_times() const {
  // @@protoc_insertion_point(field_list:CPlayer_GetUserStats_Response.Stats.unlock_times)
  return unlock_times_;
}

// -------------------------------------------------------------------

// CPlayer_GetUserStats_Response

// optional bytes sha_schema = 1;
inline bool CPlayer_GetUserStats_Response::_internal_has_sha_schema() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response::has_sha_schema() const {
  return _internal_has_sha_schema();
}
inline void CPlayer_GetUserStats_Response::clear_sha_schema() {
  sha_schema_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CPlayer_GetUserStats_Response::sha_schema() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.sha_schema)
  return _internal_sha_schema();
}
inline void CPlayer_GetUserStats_Response::set_sha_schema(const std::string& value) {
  _internal_set_sha_schema(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.sha_schema)
}
inline std::string* CPlayer_GetUserStats_Response::mutable_sha_schema() {
  // @@protoc_insertion_point(field_mutable:CPlayer_GetUserStats_Response.sha_schema)
  return _internal_mutable_sha_schema();
}
inline const std::string& CPlayer_GetUserStats_Response::_internal_sha_schema() const {
  return sha_schema_.Get();
}
inline void CPlayer_GetUserStats_Response::_internal_set_sha_schema(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CPlayer_GetUserStats_Response::set_sha_schema(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CPlayer_GetUserStats_Response.sha_schema)
}
inline void CPlayer_GetUserStats_Response::set_sha_schema(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CPlayer_GetUserStats_Response.sha_schema)
}
inline void CPlayer_GetUserStats_Response::set_sha_schema(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  sha_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CPlayer_GetUserStats_Response.sha_schema)
}
inline std::string* CPlayer_GetUserStats_Response::_internal_mutable_sha_schema() {
  _has_bits_[0] |= 0x00000001u;
  return sha_schema_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CPlayer_GetUserStats_Response::release_sha_schema() {
  // @@protoc_insertion_point(field_release:CPlayer_GetUserStats_Response.sha_schema)
  if (!_internal_has_sha_schema()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return sha_schema_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CPlayer_GetUserStats_Response::set_allocated_sha_schema(std::string* sha_schema) {
  if (sha_schema != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sha_schema_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sha_schema,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CPlayer_GetUserStats_Response.sha_schema)
}

// optional uint32 crc_stats = 2;
inline bool CPlayer_GetUserStats_Response::_internal_has_crc_stats() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response::has_crc_stats() const {
  return _internal_has_crc_stats();
}
inline void CPlayer_GetUserStats_Response::clear_crc_stats() {
  crc_stats_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response::_internal_crc_stats() const {
  return crc_stats_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CPlayer_GetUserStats_Response::crc_stats() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.crc_stats)
  return _internal_crc_stats();
}
inline void CPlayer_GetUserStats_Response::_internal_set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  crc_stats_ = value;
}
inline void CPlayer_GetUserStats_Response::set_crc_stats(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_crc_stats(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.crc_stats)
}

// optional bytes schema = 3;
inline bool CPlayer_GetUserStats_Response::_internal_has_schema() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CPlayer_GetUserStats_Response::has_schema() const {
  return _internal_has_schema();
}
inline void CPlayer_GetUserStats_Response::clear_schema() {
  schema_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CPlayer_GetUserStats_Response::schema() const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.schema)
  return _internal_schema();
}
inline void CPlayer_GetUserStats_Response::set_schema(const std::string& value) {
  _internal_set_schema(value);
  // @@protoc_insertion_point(field_set:CPlayer_GetUserStats_Response.schema)
}
inline std::string* CPlayer_GetUserStats_Response::mutable_schema() {
  // @@protoc_insertion_point(field_mutable:CPlayer_GetUserStats_Response.schema)
  return _internal_mutable_schema();
}
inline const std::string& CPlayer_GetUserStats_Response::_internal_schema() const {
  return schema_.Get();
}
inline void CPlayer_GetUserStats_Response::_internal_set_schema(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CPlayer_GetUserStats_Response::set_schema(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  schema_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CPlayer_GetUserStats_Response.schema)
}
inline void CPlayer_GetUserStats_Response::set_schema(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CPlayer_GetUserStats_Response.schema)
}
inline void CPlayer_GetUserStats_Response::set_schema(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CPlayer_GetUserStats_Response.schema)
}
inline std::string* CPlayer_GetUserStats_Response::_internal_mutable_schema() {
  _has_bits_[0] |= 0x00000002u;
  return schema_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CPlayer_GetUserStats_Response::release_schema() {
  // @@protoc_insertion_point(field_release:CPlayer_GetUserStats_Response.schema)
  if (!_internal_has_schema()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return schema_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CPlayer_GetUserStats_Response::set_allocated_schema(std::string* schema) {
  if (schema != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  schema_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), schema,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CPlayer_GetUserStats_Response.schema)
}

// repeated .CPlayer_GetUserStats_Response.Stats stats = 4;
inline int CPlayer_GetUserStats_Response::_internal_stats_size() const {
  return stats_.size();
}
inline int CPlayer_GetUserStats_Response::stats_size() const {
  return _internal_stats_size();
}
inline void CPlayer_GetUserStats_Response::clear_stats() {
  stats_.Clear();
}
inline ::CPlayer_GetUserStats_Response_Stats* CPlayer_GetUserStats_Response::mutable_stats(int index) {
  // @@protoc_insertion_point(field_mutable:CPlayer_GetUserStats_Response.stats)
  return stats_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Stats >*
CPlayer_GetUserStats_Response::mutable_stats() {
  // @@protoc_insertion_point(field_mutable_list:CPlayer_GetUserStats_Response.stats)
  return &stats_;
}
inline const ::CPlayer_GetUserStats_Response_Stats& CPlayer_GetUserStats_Response::_internal_stats(int index) const {
  return stats_.Get(index);
}
inline const ::CPlayer_GetUserStats_Response_Stats& CPlayer_GetUserStats_Response::stats(int index) const {
  // @@protoc_insertion_point(field_get:CPlayer_GetUserStats_Response.stats)
  return _internal_stats(index);
}
inline ::CPlayer_GetUserStats_Response_Stats* CPlayer_GetUserStats_Response::_internal_add_stats() {
  return stats_.Add();
}
inline ::CPlayer_GetUserStats_Response_Stats* CPlayer_GetUserStats_Response::add_stats() {
  // @@protoc_insertion_point(field_add:CPlayer_GetUserStats_Response.stats)
  return _internal_add_stats();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPlayer_GetUserStats_Response_Stats >&
CPlayer_GetUserStats_Response::stats() const {
  // @@protoc_insertion_point(field_list:CPlayer_GetUserStats_Response.stats)
  return stats_;
}

// -------------------------------------------------------------------

// CContentServerDirectory_GetManifestRequestCode_Request

// optional uint32 app_id = 1;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_app_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_app_id() const {
  return _internal_has_app_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_app_id() {
  app_id_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::_internal_app_id() const {
  return app_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::app_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.app_id)
  return _internal_app_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  app_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_app_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.app_id)
}

// optional uint32 depot_id = 2;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_depot_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_depot_id() const {
  return _internal_has_depot_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_depot_id() {
  depot_id_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::_internal_depot_id() const {
  return depot_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CContentServerDirectory_GetManifestRequestCode_Request::depot_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.depot_id)
  return _internal_depot_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  depot_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_depot_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_depot_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.depot_id)
}

// optional uint64 manifest_id = 3;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_manifest_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_manifest_id() const {
  return _internal_has_manifest_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_manifest_id() {
  manifest_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Request::_internal_manifest_id() const {
  return manifest_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Request::manifest_id() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.manifest_id)
  return _internal_manifest_id();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  manifest_id_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_manifest_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_manifest_id(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.manifest_id)
}

// optional string app_branch = 4;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_app_branch() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_app_branch() const {
  return _internal_has_app_branch();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_app_branch() {
  app_branch_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::app_branch() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  return _internal_app_branch();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const std::string& value) {
  _internal_set_app_branch(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::mutable_app_branch() {
  // @@protoc_insertion_point(field_mutable:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  return _internal_mutable_app_branch();
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::_internal_app_branch() const {
  return app_branch_.Get();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_app_branch(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_app_branch(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  app_branch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::_internal_mutable_app_branch() {
  _has_bits_[0] |= 0x00000001u;
  return app_branch_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::release_app_branch() {
  // @@protoc_insertion_point(field_release:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
  if (!_internal_has_app_branch()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return app_branch_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_allocated_app_branch(std::string* app_branch) {
  if (app_branch != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  app_branch_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_branch,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CContentServerDirectory_GetManifestRequestCode_Request.app_branch)
}

// optional string branch_password_hash = 5;
inline bool CContentServerDirectory_GetManifestRequestCode_Request::_internal_has_branch_password_hash() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Request::has_branch_password_hash() const {
  return _internal_has_branch_password_hash();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::clear_branch_password_hash() {
  branch_password_hash_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::branch_password_hash() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  return _internal_branch_password_hash();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const std::string& value) {
  _internal_set_branch_password_hash(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::mutable_branch_password_hash() {
  // @@protoc_insertion_point(field_mutable:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  return _internal_mutable_branch_password_hash();
}
inline const std::string& CContentServerDirectory_GetManifestRequestCode_Request::_internal_branch_password_hash() const {
  return branch_password_hash_.Get();
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::_internal_set_branch_password_hash(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_branch_password_hash(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  branch_password_hash_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::_internal_mutable_branch_password_hash() {
  _has_bits_[0] |= 0x00000002u;
  return branch_password_hash_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CContentServerDirectory_GetManifestRequestCode_Request::release_branch_password_hash() {
  // @@protoc_insertion_point(field_release:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
  if (!_internal_has_branch_password_hash()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return branch_password_hash_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CContentServerDirectory_GetManifestRequestCode_Request::set_allocated_branch_password_hash(std::string* branch_password_hash) {
  if (branch_password_hash != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  branch_password_hash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), branch_password_hash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CContentServerDirectory_GetManifestRequestCode_Request.branch_password_hash)
}

// -------------------------------------------------------------------

// CContentServerDirectory_GetManifestRequestCode_Response

// optional uint64 manifest_request_code = 1;
inline bool CContentServerDirectory_GetManifestRequestCode_Response::_internal_has_manifest_request_code() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CContentServerDirectory_GetManifestRequestCode_Response::has_manifest_request_code() const {
  return _internal_has_manifest_request_code();
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::clear_manifest_request_code() {
  manifest_request_code_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Response::_internal_manifest_request_code() const {
  return manifest_request_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CContentServerDirectory_GetManifestRequestCode_Response::manifest_request_code() const {
  // @@protoc_insertion_point(field_get:CContentServerDirectory_GetManifestRequestCode_Response.manifest_request_code)
  return _internal_manifest_request_code();
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::_internal_set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  manifest_request_code_ = value;
}
inline void CContentServerDirectory_GetManifestRequestCode_Response::set_manifest_request_code(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_manifest_request_code(value);
  // @@protoc_insertion_point(field_set:CContentServerDirectory_GetManifestRequestCode_Response.manifest_request_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_slssteam_5fservicemethods_2eproto
